modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hexcombat"
version = "${version}"
displayName = "Dummy Hex Casting Addon"
logoFile = "icon.png"
authors = "artynova"
description = '''
Describe me!
'''

[[dependencies.hexcombat]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcombat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcombat]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcombat]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3,)"
ordering = "NONE"
side = "BOTH"
