# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.10
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: Sofistico
book_id: hexcasting:hexcombat
default_branch: main
github_repo: HexCombat
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexcombatModPlugin
hexdoc_plugin_classname: HexcombatPlugin
java_lang:
    ext: java
    src: java
java_package: common/src/main
mod_display_name: HexCombat
modid: hexcombat
multiloader: true
package_export_root: doc/src/hexdoc_hexcombat/_export
package_name: hexdoc-hexcombat
package_slug: hexdoc_hexcombat
package_src: doc/src/hexdoc_hexcombat
pages_url: https://sofistico.github.io/HexCombat/
pattern_regex:
    per_world_value: 'true'
    regex: HexPattern\.fromAngles\("(?P<signature>[qweasd]+)", HexDir\.(?P<startdir>\w+)\),\s*modLoc\("(?P<name>[^"]+)"\)[^;]+?(?:makeConstantOp|Op\w+|Widget\.\w+)(?:[^;]*(?P<is_per_world>true)\);)?
pattern_registry: registry/HexCombatPatternRegistry.java
